---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment  # The name of the Deployment is "nodejs-deployment".
spec:
  selector:
    matchLabels: 
      app: mongo  # The selector specifies that the Deployment will manage Pods with the label "app: nodejs".
  replicas: 3  # Specifies that three replicas (Pods) of the application should be running at any time.
  template:
    metadata: 
      labels:
        app: mongo  # Labels applied to the Pods created by this Deployment. They must match the selector.
    spec:
      containers:
      - name: mongo  # The name of the container within the Pod.
        image: hosuaa/mongo:v1  # The Docker image to use for this container.
        ports:
        - containerPort: 27017