---
apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  namespace: default
spec:
  ports: 
  - nodePort: 30001 #range is 30000-32768. if you dont specify, it will select randomly
    port: 27017 # host
    targetPort: 27017 # container
  selector:
    app: mongo
  type: NodePort # also LoadBalancer - for local use cluster ip