---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-svc
  namespace: default
spec:
  ports: 
  - nodePort: 30002 #range is 30000-32768. if you dont specify, it will select randomly
    port: 3000 # host
    targetPort: 3000 # container
  selector:
    app: nodejs
  type: NodePort # also LoadBalancer - for local use cluster ip

# kubectl exec pod-name  env node seeds/seed.js