---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: default
spec:
  ports: 
  - nodePort: 30001 #range is 30000-32768. if you dont specify, it will select randomly
    port: 80 # host
    targetPort: 80 # container
  selector:
    app: nginx
  type: NodePort # also LoadBalancer - for local use cluster ip
